# Generated by Django 4.1.3 on 2022-12-04 11:06

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(help_text='Descripción de la consulta')),
                ('nombre', models.TextField(help_text='Precio')),
                ('apellidos', models.TextField(help_text='Apellidos')),
                ('nif', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('email', models.TextField(help_text='Email')),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
            ],
            options={
                'db_table': 'main_incidencia',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('autor', models.TextField(help_text='Autor')),
                ('sinopsis', models.TextField(help_text='Redacta la sinopsis')),
                ('precio', models.FloatField(help_text='Precio')),
                ('categoria', models.CharField(choices=[('Geografía / Turismo', 'Geografía-Turismo'), ('Aspectos Legales', 'Aspectos Legales'), ('Ensayos / Novelas', 'Ensayos-Novelas'), ('Textos Académicos', 'Textos Académicos'), ('Arte - Bellas Artes', 'Arte_Bellas Artes'), ('Multimedia', 'Multimedia'), ('Ciencia', 'Ciencia'), ('Bases de datos', 'Bases de datos'), ('GNU / Linux', 'GNU-Linux'), ('Música', 'Música'), ('Marketing / Business', 'Marketing-Business'), ('Web 2.0 y Social Media', 'Web 2.0 y Social Media'), ('Otros Lenguajes', 'Otros Lenguajes'), ('Cómics', 'Cómics'), ('SEO / SEM', 'SEO-SEM'), ('Tecnología', 'Tecnología'), ('Metodologías Ágiles', 'Metodologías Ágiles'), ('Fundamentos de la Música', 'Fundamentos de la Música'), ('Programación', 'Programación'), ('Javascript / AJAX', 'Javascript-AJAX'), ('Accesibilidad / Usabilidad', 'Accesibilidad-Usabilidad'), ('CSS', 'CSS'), ('Desarrollo Web', 'Desarrollo Web'), ('Cine', 'Cine'), ('MagPi', 'MagPi'), ('880 Gamer', '880 Gamer'), ('Robótica', 'Robótica'), ('Matemáticas', 'Matemáticas'), ('Información', 'Información'), ('Software General', 'Software General'), ('Filosofía', 'Filosofía'), ('HackSpace', 'HackSpace'), ('Ajedrez', 'Ajedrez'), ('Historia', 'Historia'), ('Hardware', 'Hardware'), ('Redes y Sys Admin', 'Redes y Sys Admin'), ('Retroinformática', 'Retroinformática'), ('Electrónica', 'Electrónica'), ('Herramientas', 'Herramientas'), ('Idiomas', 'Idiomas'), ('Educación', 'Educación'), ('Diseño / 3D', 'Diseño-3D'), ('Control de Versiones', 'Control de Versiones'), ('Atari', 'Atari'), ('Algoritmos', 'Algoritmos'), ('Hello World', 'Hello World')], max_length=255)),
                ('stock', models.IntegerField(help_text='Stock')),
                ('imagen', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='main/'), upload_to='static/images', verbose_name='Imagen')),
                ('escaparate', models.BooleanField(default=False)),
                ('formato', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'main_libro',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('numero_pedido', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('direccion', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('localidad', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('provincia', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('codigo_postal', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nombre', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('apellidos', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('numero_telefono', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('en_tienda', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('EN TIENDA', 'En Tienda')], default='Procesando', max_length=20)),
                ('modo_de_pago', models.CharField(blank=True, choices=[('card', 'Tarjeta de crédito'), ('refund', 'Contrareembolso')], max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibrosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.libro')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido')),
            ],
        ),
    ]
